# ----
# Site

title: frienddl.io
url: "https://frienddl.io"
baseurl:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: images/logo.png
description: Friend finder tool for skribbl.io
author:
  name: Blake Gearin
  email:
  twitter: bl4kers
social:
  name:
  links:

contact_settings:
  form_action: 'https://formspree.io/mzbjqrjz'
  confirmation_url: '/thanks'
  email_subject: 'Website form submission'
  send_button_text: 'Send Message'

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: ""
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "html/index.html"
    values:
      layout: "default"
  -
    scope:
      path: "html/support.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window
